### ISSUE TITLE
Weather API Research

### ISSUE THREAD

**Issue by anxsaiyuki** [IndecipherableSuggestions/RoadTripify#2]

**Comment by cwillens** [comment]
I set up an account with the accuweather api. To get hourly forecast data for a location, you first have to send a request for a location key (where the input parameters are latitude and longitude).

Location key request info:
- api docs: http://developer.accuweather.com/accuweather-locations-api/apis/get/locations/v1/cities/geoposition/search
- url: 'http://dataservice.accuweather.com/locations/v1/cities/geoposition/search'
- required options: apikey, q (a string of latitude,longitude)
- optional options: language (en-us), details (true), toplevel (false)
- returns json data. Variable of interest is Key

Hourly forecast request info:
- api docs: http://developer.accuweather.com/accuweather-forecast-api/apis/get/forecasts/v1/hourly/12hour/%7BlocationKey%7D
- url: 'http://dataservice.accuweather.com/forecasts/v1/hourly/12hour/' + locationKey
- required options: apikey
- optional options: language (en-us), details (true), metric (false)
- returns json data, one object for each hour in the 12 hour period
- relevant variables: DateTime, Temperature, RealFeelTemperature, Wind, Visibility, RainProbability, SnowProbability, IceProbability, CloudCover
